// Regenerate the FULL public.exercise_facts seed from the source catalogue (src/data/exercises.ts +
// muscles.ts). exercise_facts is a deterministic projection of the catalogue per the contract in
// src/__tests__/analytics-facts.test.ts:
//   is_bodyweight_lift = equipment ∋ 'bodyweight' AND category ∈ {compound, isolation}
//   regions            = DISTINCT MUSCLES[primary].region
// The original 55 rows were seeded out-of-band (only the 2 kettlebell additions live in a migration),
// so a fresh DB built from migrations alone would be missing them. This makes schema-as-code complete.
//
// Run: node --experimental-strip-types scripts/gen-exercise-facts-seed.ts
import { writeFileSync } from 'node:fs'
import { EXERCISES } from '../src/data/exercises.ts'
import { MUSCLES } from '../src/data/muscles.ts'

const facts = EXERCISES.map((ex) => {
  const isBw = ex.equipment.includes('bodyweight') && (ex.category === 'compound' || ex.category === 'isolation')
  const regions = [...new Set(ex.primary.map((m) => MUSCLES[m].region))]
  return { id: ex.id, isBw, regions }
})

const values = facts
  .map((f) => `  ('${f.id}', ${f.isBw}, '{${f.regions.join(',')}}')`)
  .join(',\n')

const sql = `-- AUTO-GENERATED by scripts/gen-exercise-facts-seed.ts — do not edit by hand.
-- Full public.exercise_facts seed (${facts.length} rows) derived from the source catalogue
-- (src/data/exercises.ts + muscles.ts) per the analytics-facts contract:
--   is_bodyweight_lift = equipment ∋ 'bodyweight' AND category ∈ {compound, isolation}
--   regions            = DISTINCT MUSCLES[primary].region
-- Regenerate after any catalogue change: node --experimental-strip-types scripts/gen-exercise-facts-seed.ts
insert into public.exercise_facts (exercise_id, is_bodyweight_lift, regions) values
${values}
on conflict (exercise_id) do update
  set is_bodyweight_lift = excluded.is_bodyweight_lift,
      regions            = excluded.regions;
`

const out = 'supabase/migrations/20260626190000_seed_exercise_facts_full_catalogue.sql'
writeFileSync(out, sql)
console.log(`wrote ${facts.length} facts → ${out}`)
