// Compile the bundled exercise catalogues (src/data/exercises.ts → EXERCISES and src/data/rehab.ts →
// REHAB_EXERCISES) into public.exercises rows and either PUSH them with a service-role client, or EMIT
// a deterministic, idempotent seed migration. This keeps the DB catalogue "schema-as-code": the bundled
// set is the source, the DB is a managed overlay. Rehab exercises carry category:'rehab' and live in
// the same table (the app partitions them into the rehab pool at merge time).
//
// Validates EVERY bundled exercise through the shared exerciseSchema first, so a bad edit to EXERCISES
// or REHAB_EXERCISES (an unknown muscle/equipment/category, bad difficulty, etc.) fails the script
// loud — doubling as a CI guard.
//
// Run (push to DB):
//   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
//     node --experimental-strip-types scripts/seed-exercises.ts
// Run (emit SQL migration instead — preferred, schema-as-code):
//   node --experimental-strip-types scripts/seed-exercises.ts --emit-sql
import { writeFileSync } from 'node:fs'
import { createClient } from '@supabase/supabase-js'
import { EXERCISES, REHAB_EXERCISES } from '../src/data/exercises.ts'
import { validateExerciseRow } from '../src/lib/exerciseSchema.ts'

interface ExerciseRow {
  id: string
  data: unknown
  sort: number
  active: boolean
}

/** Build the rows from both bundled catalogues, validating each through the shared schema. Throws on
 *  the first bad one. */
function buildRows(): ExerciseRow[] {
  // union the main library and the rehab catalogue (rehab carries category:'rehab'); the app routes
  // rehab rows to the rehab pool at merge time, so one table holds both.
  return [...EXERCISES, ...REHAB_EXERCISES].map((exercise, index) => {
    const res = validateExerciseRow(exercise)
    if (!res.ok) {
      throw new Error(
        `Bundled exercise "${exercise.id}" is invalid (${res.reason}${res.detail ? `: ${res.detail}` : ''}). ` +
          'Fix src/data/exercises.ts or src/data/rehab.ts before seeding.',
      )
    }
    // Store the VALIDATED+normalized exercise — what the app would accept back from the DB.
    return { id: exercise.id, data: res.exercise, sort: index, active: true }
  })
}

/** Two-space UTC stamp → migration filename, matching the existing migrations' naming. */
function utcStamp(): string {
  const d = new Date()
  const p = (n: number, w = 2) => String(n).padStart(w, '0')
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(
    d.getUTCMinutes(),
  )}${p(d.getUTCSeconds())}`
}

/** Render the idempotent insert…on conflict do update SQL. Deterministic for a given catalogue. */
function emitSql(rows: ExerciseRow[]): string {
  const values = rows
    .map((r) => {
      // pg literal: single-quote the JSON and double any embedded single quotes.
      const json = JSON.stringify(r.data).replace(/'/g, "''")
      return `  ('${r.id}', '${json}'::jsonb, ${r.sort}, ${r.active})`
    })
    .join(',\n')

  return `-- AUTO-GENERATED by scripts/seed-exercises.ts — do not edit by hand.
-- Seed public.exercises from the bundled catalogues (src/data/exercises.ts + src/data/rehab.ts), ${rows.length} rows.
-- Idempotent: re-running upserts by id. Regenerate after a catalogue change:
--   node --experimental-strip-types scripts/seed-exercises.ts --emit-sql
insert into public.exercises (id, data, sort, active) values
${values}
on conflict (id) do update
  set data   = excluded.data,
      sort   = excluded.sort,
      active = excluded.active;
`
}

async function pushToDb(rows: ExerciseRow[]): Promise<void> {
  const url = process.env.SUPABASE_URL
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !serviceRoleKey) {
    throw new Error(
      'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. Set both to push, or pass --emit-sql to ' +
        'write a migration instead.',
    )
  }
  const client = createClient(url, serviceRoleKey, { auth: { persistSession: false } })
  const { error } = await client.from('exercises').upsert(rows, { onConflict: 'id' })
  if (error) throw new Error(`upsert failed: ${error.message}`)
  console.log(`upserted ${rows.length} exercises into public.exercises`)
}

async function main(): Promise<void> {
  const rows = buildRows()
  if (process.argv.includes('--emit-sql')) {
    const out = `supabase/migrations/${utcStamp()}_seed_exercises_catalogue.sql`
    writeFileSync(out, emitSql(rows))
    console.log(`wrote ${rows.length} exercises → ${out}`)
    return
  }
  await pushToDb(rows)
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
