// Compile the bundled plan catalogue (src/data/plans.ts → PLANS) into public.plans rows and either
// PUSH them with a service-role client, or EMIT a deterministic, idempotent seed migration. This keeps
// the DB catalogue "schema-as-code": the bundled set is the source, the DB is a managed overlay.
//
// Validates EVERY bundled plan through the shared planSchema first, so a bad edit to PLANS (incl. a
// dangling exercise id or an out-of-union enum) fails the script loud — doubling as a CI guard.
//
// Run (push to DB):
//   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
//     node --experimental-strip-types scripts/seed-plans.ts
// Run (emit SQL migration instead — preferred, schema-as-code):
//   node --experimental-strip-types scripts/seed-plans.ts --emit-sql
import { writeFileSync } from 'node:fs'
import { createClient } from '@supabase/supabase-js'
import { PLANS } from '../src/data/plans.ts'
import { validatePlanRow } from '../src/lib/planSchema.ts'

interface PlanRow {
  id: string
  data: unknown
  sort: number
  active: boolean
}

/** Build the rows, validating each bundled plan through the shared schema. Throws on the first bad one. */
function buildRows(): PlanRow[] {
  return PLANS.map((plan, index) => {
    const res = validatePlanRow(plan)
    if (!res.ok) {
      throw new Error(
        `Bundled plan "${plan.id}" is invalid (${res.reason}${res.detail ? `: ${res.detail}` : ''}). ` +
          'Fix src/data/plans.ts before seeding.',
      )
    }
    // Store the VALIDATED+normalized plan (custom:false, clamped reps) — what the app would accept back.
    return { id: plan.id, data: res.plan, sort: index, active: true }
  })
}

/** Two-space UTC stamp → migration filename, matching the existing migrations' naming. */
function utcStamp(): string {
  const d = new Date()
  const p = (n: number, w = 2) => String(n).padStart(w, '0')
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(
    d.getUTCMinutes(),
  )}${p(d.getUTCSeconds())}`
}

/** Render the idempotent insert…on conflict do update SQL. Deterministic for a given catalogue. */
function emitSql(rows: PlanRow[]): string {
  const values = rows
    .map((r) => {
      // pg literal: single-quote the JSON and double any embedded single quotes.
      const json = JSON.stringify(r.data).replace(/'/g, "''")
      return `  ('${r.id}', '${json}'::jsonb, ${r.sort}, ${r.active})`
    })
    .join(',\n')

  return `-- AUTO-GENERATED by scripts/seed-plans.ts — do not edit by hand.
-- Seed public.plans from the bundled catalogue (src/data/plans.ts → PLANS), ${rows.length} rows.
-- Idempotent: re-running upserts by id. Regenerate after a catalogue change:
--   node --experimental-strip-types scripts/seed-plans.ts --emit-sql
insert into public.plans (id, data, sort, active) values
${values}
on conflict (id) do update
  set data   = excluded.data,
      sort   = excluded.sort,
      active = excluded.active;
`
}

async function pushToDb(rows: PlanRow[]): Promise<void> {
  const url = process.env.SUPABASE_URL
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !serviceRoleKey) {
    throw new Error(
      'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. Set both to push, or pass --emit-sql to ' +
        'write a migration instead.',
    )
  }
  const client = createClient(url, serviceRoleKey, { auth: { persistSession: false } })
  const { error } = await client.from('plans').upsert(rows, { onConflict: 'id' })
  if (error) throw new Error(`upsert failed: ${error.message}`)
  console.log(`upserted ${rows.length} plans into public.plans`)
}

async function main(): Promise<void> {
  const rows = buildRows()
  if (process.argv.includes('--emit-sql')) {
    const out = `supabase/migrations/${utcStamp()}_seed_plans_catalogue.sql`
    writeFileSync(out, emitSql(rows))
    console.log(`wrote ${rows.length} plans → ${out}`)
    return
  }
  await pushToDb(rows)
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
